name: Branch Push
on: push
jobs:
  test:
    name: Jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run tests
        run: npm t
